### ISSUE TITLE
Add support for syslog 4

### ISSUE THREAD

**Issue by oysterpack** [daboross/fern#29]
syslog 4 provides support for formatting messages in RFC 3164 or RFC 5424 format

**Comment by daboross** [comment]
I don't think we'll be able to support RFC5424 formatting in fern since it requires extra data (I think?), but we can definitely use syslog 4 RFC 3164 logging.

syslog version 3 required specialized support from fern because it used an older version of log, but the new syslog should "just work" with something like:

```rust
extern crate log;
extern crate syslog;
extern crate fern;

fn main() {
    let formatter = syslog::Formatter3164 {
        facility: syslog::Facility::LOG_USER,
        hostname: None,
        process: "myprogram".into(),
        pid: 42,
    };

    let syslog = syslog::unix(formatter)
        .expect("expected to connect to syslog");

    fern::Dispatch::new()
        // ...
        .chain(Box::new(syslog::BasicLogger::new(syslog)) as Box<log::Log>)
        // ...
}
```

I'll keep this issue open for adding documentation on how to do this to fern, or updating the old documentation that currently refers to syslog 0.3.

**Comment by daboross** [comment]
On second thought, it would be nice to have more "direct" integration with syslog 4.0.

I don't have a ton of time at the moment, but if anyone wants to try this, here's what needs to be done:

- Add dependency on [`syslog3`](https://crates.io/crates/syslog3). We need this so that we can depend on both syslog version 3 and 4, for backwards compatibility. (feature name is already "syslog-3" so we should be good there)
- Change all integration with `syslog` into usages of `syslog3` (also change feature to depend on "syslog3")
- Change `syslog = { version = "3" ... }` into `syslog = { version = "4" ... }`
- Add integration into syslog version 4 under a "syslog-4" feature flag. This should be almost exactly the same as syslog-3 integration.
- Change `src/syslog.rs` to use syslog 4 rather than syslog 3. This file just has documentation.
- Clean up any extra references to syslog version 3 in documentation.

**Comment by daboross** [comment]
Support has been added, and will be released in the next version!

The new changes do support RFC5424, but in order to use it you'll need to supply a manual transform from `log::Record` into the `(i32, HashMap<String, HashMap<String, String>>, String)` that `syslog` expects.
