### ISSUE TITLE
Could not comile datebased log example 

### ISSUE THREAD

**Issue by toplinuxsir** [daboross/fern#43]
Could not comile datebased log example 

At windows os, 

Error : Could not find DateBasedLogFile in fern

**Comment by daboross** [comment]
`DateBased` loggers were merged into master earlier this year, but a new version of fern hadn't been released yet. Because of this, it wouldn't have been possible to use them with the crates.io version.

As of tonight, though, I've made a few more changes to the date-based logger, and released fern-0.5.9! This should now function.

**Comment by IsaccBarker** [comment]
DateBased does not seem to exist in version 6.0.0 either.

**Comment by Winches** [comment]
@daboross I still facing the same issue in version 0.6.1(windows).
