### ISSUE TITLE
newlines in output files? 

### ISSUE THREAD

**Issue by waynenilsen** [daboross/fern#5]
This may not just be for this library, but I used this on windows and it created an output file with unix end-of-line characters. I'm used to python doing magic newline conversions in a windows environment. I couldn't seem to find where the newline character was appended to the message but perhaps using something akin to the Python [`os.linesep`](https://docs.python.org/3/library/os.html#os.linesep) would be better?

**Comment by daboross** [comment]
The behavior is defined in https://github.com/daboross/fern-rs/blob/master/src/loggers.rs#L109.

However, there doesn't currently seem to be a way to get the system line separator defined in the rust standard library. Do you think a way to set the line separator in the logger configuration would suffice for this (defaulting to `\n`)?

**Comment by waynenilsen** [comment]
I added an [rfc](https://github.com/rust-lang/rfcs/issues/1092) so we'll see if they want to add that functionality or not. I think it is pretty low hanging fruit for the 1.0 release.

**Comment by SimonSapin** [comment]
This doesn’t have to be in the standard library, you can use `cfg` attributes for conditional compilation:

```
#[cfg(windows)]
const NEWLINE: &'static str = "\r\n";

#[cfg(note(windows))]
const NEWLINE: &'static str = "\n";
```

**Comment by waynenilsen** [comment]
It doesn't have to be but it certainly could be. I just wanted to give the rust team a chance to add it as a feature if they want to.

**Comment by daboross** [comment]
Since there hasn't been that much discussion on the rust issue, I'm just going to implement a configurable value for now.

It seems better (to me at least) to not implicitly change behavior depending on platform, and instead allow the user of the library to explicitly choose what newline separator they want (if it isn't \n).

**Comment by daboross** [comment]
Since `fern` 0.3.5, setting a custom line separator has been supported. In `fern` 0.4.0, this can be done with [`Output::file`].

I'm going to close now, as I think it's reasonable to let the user decide if they need platform-specific line endings. I'd rather not have `fern` decide this for the user, but if `rust` ever adds the line-ending constant mentioned above, I would be glad to re-visit this!

[`Output::file`]: https://dabo.guru/rust/fern/fern/struct.Output.html#method.file
