### ISSUE TITLE
Moving to reopen 1.0

### ISSUE THREAD

**Issue by vorner** [daboross/fern#66]
Hello

I've released reopen 1.0 and intend to consider it stable (well, it didn't need any touching for 2 years, so I guess it is „complete“). And I wanted to send a pull request with update, but I'm a bit unsure about one thing.

It's turned on by the `reopen-03` feature. Is it OK to remove that one and replace by a `reopen-1` or do you want to support both in parallel?

**Comment by daboross** [comment]
Hi!

I'd be happy to accept a PR.

Ideally, I'd like to support both in parallel, similar to how the multiple `syslog` features work at the moment. Feel free to just replace all documentation references with referencing `reopen-1`, and leave the older one as undocumented - I'd just like to keep it in there so that we can stay on minor version updates and keep compatibility.

Thank you for looking into this!
