### ISSUE TITLE
Chaining vec of Dispatch

### ISSUE THREAD

**Issue by mikart143** [daboross/fern#69]
Hello!
How can I chain vec of fern::Dispatch ?
```
    let mut logger_base = Dispatch::new();
    logger_base.level(log_level);

    for logger in loggers.iter(){
        logger_base.chain(logger)
    }

    logger_base.apply()?;
```

I am struggling with this for a whole day

**Comment by daboross** [comment]
My apologies for taking so long to get to this!

The trick is that all methods take `self` and return an owned Dispatch, so you need to re-assign to the variable in order to get this to work. In addition, you need to take the loggers by value, so using `.iter()`, which gives you references, won't work:

```
let loggers = vec![Dispatch::new(), Dispatch::new(), Dispatch::new()];
let mut logger_base = Dispatch::new();
logger_base.level(log_level);

for logger in loggers {
    logger_base = logger_base.chain(logger);
}

logger_base.apply()?;
```

**Comment by xenago** [comment]
>you need to re-assign to the variable in order to get this to work.

This was super helpful to me, thank you! Wanted to have various different loggers but wasn't sure which ones beforehand. Using a mutable vector of loggers and then iterating over them as you did there was perfect.
